[package]
name = "kompute"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
debug_layer = []

[dependencies]
ash = "0.37.3+1.3.251"
log = "0.4.20"
shaderc = "0.8.3"
num = "0.4.1"
env_logger = "0.10.1"